## Fixes the path used so that codecov can properly display files and diff
## When coverage is uploaded from CI, the absolute path (`/go/src/boscoin.io...`)
## is present in the report, which Codecov cannot match by default
fixes:
  - "boscoin.io/sebak/::"  # Remove the prefix
