package sebak_error

var ErrorBlockAlreadyExists = NewError(100, "already exists in block")
var ErrorHashDoesNotMatch = NewError(101, "`Hash` does not match")
var ErrorSignatureVerificationFailed = NewError(102, "signature verification failed")
var ErrorBadPublicAddress = NewError(103, "failed to parse public address")
var ErrorInvalidFee = NewError(104, "invalid fee")
var ErrorInvalidOperation = NewError(105, "invalid operation")
var ErrorNewButKnownMessage = NewError(106, "received new, but known message")
var ErrorInvalidState = NewError(107, "found invalid state")
var ErrorInvalidVotingThresholdPolicy = NewError(108, "invalid `VotingThresholdPolicy`")
var ErrorBallotEmptyMessage = NewError(109, "init state ballot does not have `Message`")
var ErrorInvalidHash = NewError(110, "invalid `Hash`")
var ErrorInvalidMessage = NewError(111, "invalid `Message`")
var ErrorBallotHasMessage = NewError(112, "none-init state ballot must not have `Message`")
var ErrorVotingResultAlreadyExists = NewError(113, "`VotingResult` already exists")
var ErrorVotingResultNotFound = NewError(114, "`VotingResult` not found")
var ErrorVotingResultFailedToSetState = NewError(115, "failed to set the new state to `VotingResult`")
var ErrorVotingResultNotInBox = NewError(1146, "ballot is not in here")
var ErrorBallotNoVoting = NewError(201, "ballot has no `Voting`")
var ErrorBallotNoNodeKey = NewError(202, "ballot has no `NodeKey`")
var ErrorVotingThresholdInvalidValidators = NewError(203, "invalid validators")
var ErrorBallotHasInvalidState = NewError(204, "ballot has invalid state")
var ErrorVotingResultFailedToClose = NewError(205, "failed to close `VotingResult`")
